name: Dependency Check

on: [push]

jobs:
  dependency-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generates BoM and upload to OWASP DTrack
        id: riskscoreFromDT
        uses: Quobis/action-owasp-dependecy-track-check@main
        with:
          url: "http://dtrack-dependency-track-api-server:8080"
          key: "${{ secrets.DTRACK_API_KEY }}"
          language: "nodejs"

      - name: Get the output time
        run: echo "The risk score of the project is ${{ steps.riskscoreFromDT.outputs.riskscore }}"
