name: Dependency Check

on: [push]

jobs:
  dependency-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "grepcidr"
          format: "XML"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports

      - name: Upload to Dependency-Track
        env:
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
          DTRACK_URL: "http://dtrack-dependency-track-api-server:8080"
        run: |
          curl -X POST "${DTRACK_URL}/api/v1/bom" \
            -H "Content-Type: application/xml" \
            -H "X-API-Key: ${DTRACK_API_KEY}" \
            -F 'autoCreate=true' \
            -F 'bom=${{github.workspace}}/reports/dependency-check-report.xml'
