name: Dependency Check

on: [push]

jobs:
  dependency-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install

      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          output: "./grepcidr.bom.xml"

      - name: SBOM zu DependencyTrack senden
        uses: DependencyTrack/gh-upload-sbom@v3.0.0
        with:
          protocol: "http"
          serverHostname: "dtrack-dependency-track-api-server"
          port: "8080"
          apiKey: ${{ secrets.DTRACK_API_KEY }}
          projectName: "grepcidr"
          projectVersion: "1.0.0"
          bomFilename: "./grepcidr.bom.xml"
          autoCreate: true

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "grepcidr-check"
          path: "."
          format: "HTML"
          out: "reports" # this is the default, no need to specify unless you wish to override it

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

      #- name: Run Dependency-Check
      #  uses: dependency-check/Dependency-Check_Action@main
      #  with:
      #    project: "grepcidr"
      #    path: "."
      #    format: "XML"

      #- name: Upload to Dependency-Track
      #  env:
      #    DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
      #    DTRACK_URL: "http://dtrack-dependency-track-api-server:8080"
      #  run: |
      #    curl -X POST "${DTRACK_URL}/api/v1/bom" \
      #      -H 'accept: application/xml' \
      #      -H 'Content-Type: multipart/form-data' \
      #      -H "X-API-Key: ${DTRACK_API_KEY}" \
      #      -F 'projectName=grepcidr' \
      #      -F 'parentVersion=1.0.0' \
      #      -F 'autoCreate=true' \
      #      -F 'bom=${{github.workspace}}/reports/dependency-check-report.xml'
